springdoc:
  pre-loading-enabled: true
  swagger-ui:
    path: /
    display-request-duration: true

server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 123456 # Keystore oluştururken verdiğin şifre
    key-store-type: PKCS12
    key-alias: myapp # Yukarıda kullandığın alias
spring:
  application:
    name: Hatimmatik
  h2:
    console:
      enabled: true
      path: /hatimmatik-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:./data/hatimmatik:hatimmatik-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: admin